app/profile/forms.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, Regexp, NumberRange, URL


class UserInfoForm(FlaskForm):
    age = IntegerField('年龄', validators=[NumberRange(min=12, max=80, message='年龄必须在12-80之间'),
                                         Regexp(r'^[0-9]{2}$', 0, u'年龄只能用数字')],
                       render_kw={'class': "form-control"},
                       _name="age"
                       )

    gender = SelectField('性别', validators=[DataRequired()], render_kw={'class': "form-control", "required": "required"},
                         _name="gender"
                         )
    education = SelectField('学历', render_kw={'class': "form-control"}, _name="education", )
    graduated = SelectField('学校', render_kw={'class': "form-control"}, _name="graduated"
                            )
    industry = SelectField(u'行业', render_kw={'class': "form-control"}, _name="industry"
                           )
    company = StringField(u'公司', render_kw={'class': "form-control"}, _name="company")
    position = SelectField(u'职位', render_kw={'class': "form-control"}, _name="position"
                           )
    language = SelectField(u'语言', render_kw={'class': "form-control"},
                           _name="language"
                           )
    website = StringField(u'网站', validators=[URL(message=u'URL格式不正确')], render_kw={'class': "form-control"},
                          _name="website"
                          )
    submit = SubmitField(render_kw={'class': "btn btn-info", 'value': '提交'})

app/profile/__init__.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import views

app/profile/views.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
import datetime
from ..models import User, Post, Comment, Todo, Message, UserInfo
from . import profile
from .. import db
from ..admin.views import get_c_month, get_m_days, get_day
from .forms import UserInfoForm
from ..shares import UploadToQiniu, allowed_file
import json
import os


# 用户资料页
@profile.route('/user/<username>/', methods=['GET'])
@login_required
def user_index(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('不存在用户：' + username + '！')
        return redirect(url_for('public.index'))
    if user.id != current_user.id:
        flash('您没有权限访问该页面!')
        return redirect(url_for('public.index'))
    user_ = UserInfo.query.get(user.id)
    n = get_c_month()
    days = get_m_days()
    lst = [
        Post.query.filter_by(author_id=user.id).filter(
            Post.created.between('2017-%s-%d 0:0:0' % (n, i), '2017-%s-%d 0:0:0' % (n, (i + 1)))).count()
        for i in range(1, days)]
    x = list(range(1, days))
    m = get_c_month()
    day = get_day()
    return render_template('profile/user_index.html', user=user, user_=user_,
                           title='%s的后台' % user.username,
                           menu=0, x=x, lst=lst, m=m, day=day, days=days)


# 修改用户资料
@profile.route('/modify_info/', methods=['POST', 'GET'])
@login_required
def modify_info():
    file = open(os.path.join(os.path.dirname(__file__), 'select.json'), 'r', encoding='utf-8')
    form = UserInfoForm()
    choices = json.load(file)
    form.gender.choices = choices['gender']
    form.graduated.choices = choices['graduated']
    form.position.choices = choices['position']
    form.industry.choices = choices['industry']
    form.education.choices = choices['education']
    form.language.choices = choices['language']
    file.close()
    user_ = UserInfo.query.get(current_user.id)
    if user_:
        form.age.data = user_.age
        form.gender.data = user_.gender
        form.education.data = user_.education
        form.graduated.data = user_.graduated
        form.position.data = user_.position
        form.company.data = user_.company
        form.industry.data = user_.industry
        form.language.data = user_.language
        form.website.data = user_.website
    if request.method == 'POST':
        if request.form:
            form1 = request.form
            age = form1['age'],
            gender = form1['gender'],
            education = form1['education'],
            graduated = form1['graduated'],
            position = form1['position'],
            company = form1['company'],
            industry = form1['industry'],
            language = form1['language'],
            website = form1['website'],
            user_info = UserInfo(
                age=age[0],
                gender=str(gender[0]),
                education=education[0],
                graduated=graduated[0],
                position=position[0],
                company=company[0],
                industry=industry[0],
                language=language[0],
                website=website[0],
                id=current_user.id,
            )
            if user_:
                user_.age = age[0] if age else user_.age
                user_.gender = gender[0] if gender else user_.gender
                user_.education = education[0] if education else user_.education
                user_.graduated = graduated[0] if graduated else user_.graduated
                user_.position = position[0] if position else user_.position
                user_.company = company[0] if company else user_.company
                user_.industry = industry[0] if industry else industry
                user_.language = language[0] if language else user_.language
                user_.website = website[0] if website else user_.website
            else:
                db.session.add(user_info)
                db.session.commit()
            flash('资料修改成功')
            return redirect(url_for('profile.user_index', username=current_user.username))
        if request.files['file']:
            file = request.files['file']
            if file and allowed_file(file.filename):
                domian_name = 'https://static.51qinqing.com'
                u = UploadToQiniu(file, 'avatar/')
                ret, info = u.upload()
                key = ret['key']
                current_user.avatar = domian_name + '/' + key
                return jsonify({"success": True})
            flash('文件格式不允许!')
    return render_template('profile/modify_info.html', title='修改资料', form=form)


@profile.route('/upload_zfbimg/', methods=['POST', 'GET'])
@login_required
def upload_zfbimg():
    if request.method == 'POST':
        if request.form:
            form = request.form
            if form['num']:
                current_user.zfb_num = form['num']
            flash('支付宝信息修改成功')
            return redirect(url_for('profile.user_reward_manage'))
        if request.files['file']:
            file = request.files['file']
            if allowed_file(file.filename):
                domian_name = 'https://static.51qinqing.com'
                u = UploadToQiniu(file, 'pay/zfb/')
                ret, info = u.upload()
                key = ret['key']
                current_user.zfb_img = domian_name + '/' + key
                return jsonify({"success": True})
            else:
                flash('文件格式不允许')
                return redirect(url_for('profile.upload_zfbimg'))
    return render_template('profile/upload_zfbimg.html', title='修改支付宝打赏信息')


@profile.route('/upload_wximg/', methods=['POST', 'GET'])
@login_required
def upload_wximg():
    if request.method == 'POST':
        if request.form:
            form = request.form
            if form['num']:
                current_user.wx_num = form['num']
            flash('微信信息修改成功')
            return redirect(url_for('profile.user_reward_manage'))
        if request.files['file']:
            file = request.files['file']
            if allowed_file(file.filename):
                domian_name = 'https://static.51qinqing.com'
                u = UploadToQiniu(file, 'pay/wx/')
                ret, info = u.upload()
                key = ret['key']
                current_user.wx_img = domian_name + '/' + key
                return jsonify({"success": True})
            else:
                flash('文件格式不允许')
                return redirect(url_for('profile.upload_wximg'))
    return render_template('profile/upload_wximg.html', title='修改微信打赏信息')


@profile.route('/others/<username>/', methods=['GET'])
def others(username):
    posts_ = Post.query.filter(Post.is_public == 1).order_by(Post.comment_times.desc()).limit(5)
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('不存在用户：' + username + '！')
        return redirect(url_for('public.index'))
    else:
        posts = Post.query.filter(Post.is_public == 1).filter_by(author_id=user.id)

    return render_template('profile/others.html', user=user, posts=posts,
                           title='%s的资料' % user.username,
                           posts_=posts_,
                           menu=0)


@profile.route('/user/blogs_manage/', methods=['GET'])
@login_required
def user_blogs_manage():
    posts = Post.query.filter_by(author_id=current_user.id)
    return render_template('profile/blogs_manage.html',
                           posts=posts,
                           title='博客管理',
                           menu=1)


@profile.route('/user/bolg_manage/<int:id_>/', methods=['POST', 'GET'])
@login_required
def user_blog_manage(id_):
    post = Post.query.filter_by(id=id_).first()
    user = User.query.filter_by(id=post.author_id).first()
    if post is None:
        flash('文章不存在!')
    if not current_user.is_authenticated:
        flash('请登录后再操作!')
    post.del_comments()
    post.del_tags()
    db.session.delete(post)
    db.session.commit()
    user.post_total -= 1
    flash('文章删除成功!')
    return redirect(url_for('profile.user_blogs_manage'))


@profile.route('/user/public_manage/<int:id_>/<int:public>/', methods=['POST', 'GET'])
@login_required
def user_public_manage(id_, public):
    post = Post.query.filter_by(id=id_).first()
    if not post:
        flash('文章不存在')
    post.is_public = 1 if int(public) == 1 else 0
    return redirect(url_for('profile.user_blogs_manage'))


@profile.route('/user/comments_manage/', methods=['GET'])
@login_required
def user_comments_manage():
    comments = Comment.query.filter_by(author_id=current_user.id)
    return render_template('profile/comments_manage.html',
                           comments=comments,
                           title='评论管理',
                           menu=3)


@profile.route('/user/comment_manage/<int:id_>/', methods=['POST', 'GET'])
@login_required
def user_comment_manage(id_):
    comment = Comment.query.filter_by(id=id_).first()
    if comment is None:
        flash('评论不存在!')
    if not current_user.is_authenticated:
        flash('请登录后再操作!')
    comment.delete_all_reply()
    db.session.delete(comment)
    db.session.commit()
    flash('评论删除成功!')
    return redirect(url_for('profile.user_comments_manage'))


@profile.route('/user/collects_manage/', methods=['GET'])
@login_required
def user_collects_manage():
    user = current_user
    posts = user.collected_posts()
    return render_template('profile/collects_manage.html',
                           posts=posts,
                           title='收藏管理',
                           menu=2)


@profile.route('/user/followers_manage/', methods=['GET'])
@login_required

app/templates/profile/base.html
{% extends 'bootstrap/base.html' %}

{% block head %}
    <head>
        {{ super() }}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
        <meta http-equiv="cache-control" content="no-cache">
        <meta name="description" content="这是一个基于flask的开源多用户博客系统!">
        <meta name="keywords" content="Python,博客，后端，前端,flask,redis,celery,web,入门,学习,教程,文章">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="index">
        <meta name="author" content="qyzxg,qyzxg@live.com">
        <meta name="copyright" content="qyzxg">
        <meta name="revisit-after" content="1 days">
        <link rel="shortcut icon" href="https://static.51qinqing.com/logo/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename = 'stylesheets/main.css') }}">
        <link rel="stylesheet" type="text/css"
              href="{{ url_for('static', filename = 'font-awesome/css/font-awesome.min.css') }}">
        {% include 'includes/_navbar.html' %}

        <title>{% block title %}{{ title|safe }}{% endblock %}</title>
    </head>
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/datatables.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/up_styles.css') }}">
    <style>
        .container {
            margin-top: 30px;
        }
    </style>

{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-md-2">
            <!-- 左侧的菜单 -->
            <div class="list-group" style="text-align: center">
                <a href="{{ url_for('public.edit') }}" class="btn btn-primary">发表新文章</a>
                <br>
                <br>
                <a href="{{ url_for('profile.user_index',username=current_user.username) }}"
                   class="list-group-item {% if menu==0 %} active {% endif %}">
                    <span class="glyphicon glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp我的资料
                </a>
                <a href="{{ url_for('profile.user_blogs_manage') }}"
                   class="list-group-item {% if menu==1 %} active {% endif %}"><span class="glyphicon glyphicon-pencil"
                                                                                     aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp文章管理</a>
                <a href="{{ url_for('profile.user_collects_manage') }}"
                   class="list-group-item {% if menu==2 %} active {% endif %}"><span
                        class="glyphicon glyphicon-tags" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp收藏管理</a>
                <a href="{{ url_for('profile.user_comments_manage') }}"
                   class="list-group-item {% if menu==3 %} active {% endif %}"><span class="glyphicon glyphicon-comment"
                                                                                     aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp评论管理</a>
                <a href="{{ url_for('profile.user_todos_manage') }}"
                   class="list-group-item {% if menu==4 %} active {% endif %}"><span
                        class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbspToDo管理</a>
                <a href="{{ url_for('profile.user_followers_manage') }}"
                   class="list-group-item {% if menu==5 %} active {% endif %}"><span
                        class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp好友管理</a>
                <a href="{{ url_for('profile.messages_manage') }}"
                   class="list-group-item {% if menu==6 %} active {% endif %}"><span
                        class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp消息管理</a>
                <a href="{{ url_for('profile.user_reward_manage') }}"
                   class="list-group-item {% if menu==7 %} active {% endif %}"><span
                        class="glyphicon glyphicon-yen" aria-hidden="true"></span>&nbsp&nbsp&nbsp&nbsp打赏管理</a>
            </div>
        </div>
        <div class="col-md-10">
            <!-- 右侧内容 -->
            {% block breadcrumb %}
                <ol class="breadcrumb">
                    <li><a href="{{ url_for('profile.user_index',username=current_user.username) }}">个人首页</a></li>
                    <li class="active">我的资料</li>
                </ol>
            {% endblock %}
            {% block right_content %}
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
    <div class="container">
{#        <div class="col-md-12">#}
{#            {% block footer %}#}
{#                {% include 'includes/_footer.html' %}#}
{#            {% endblock %}#}
{#        </div>#}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename ='javascripts/echarts.common.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ url_for('static', filename ='javascripts/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename ='javascripts/user_tables.js') }}" type="text/javascript"></script>
     <script src="{{ url_for('static', filename ='javascripts/jquery.filedrop.js') }}" type="text/javascript"></script>
{% endblock %}

app/templates/profile/base_other.html
{% extends 'bootstrap/base.html' %}

{% block head %}
    <head>
        {{ super() }}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
        <meta http-equiv="cache-control" content="no-cache">
        <meta name="description" content="这是一个基于flask的开源多用户博客系统!">
        <meta name="keywords" content="Python,博客，后端，前端,flask,redis,celery,web,入门,学习,教程,文章">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="index">
        <meta name="author" content="qyzxg,qyzxg@live.com">
        <meta name="copyright" content="qyzxg">
        <meta name="revisit-after" content="1 days">
        <link rel="shortcut icon" href="https://static.51qinqing.com/logo/favicon.ico" type="image/x-icon">
        {% include 'includes/_navbar.html' %}
        <title>{% block title %}{{ title|safe }}{% endblock %}</title>
    </head>
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename = 'font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'stylesheets/datatables.min.css') }}">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-md-9">
            {% block left_content %}
            {% endblock %}
        </div>
        <div class="col-md-3">
            {% block right_content %}
            {% endblock %}
        </div>
    </div>
    <div class="container">
{#        <div class="col-md-12">#}
{#            {% block footer %}#}
{#                {% include 'includes/_footer.html' %}#}
{#            {% endblock %}#}
{#        </div>#}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{#    <script src="{{ url_for('static', filename ='javascripts/jquery-2.2.1.min.js') }}" type="text/javascript"></script>#}
    <script src="{{ url_for('static', filename ='javascripts/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename ='javascripts/user_tables.js') }}" type="text/javascript"></script>
{% endblock %}




app/templates/profile/blogs_manage.html
{% extends 'profile/base.html' %}

{% block head_title %}
    {{ title }}
    <title>博客管理</title>
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ url_for('profile.user_index',username=current_user.username) }}">个人首页</a></li>
        <li class="active">博客管理</li>
    </ol>
{% endblock %}
{% block right_content %}
    {{ super() }}
    <h3>我发表的文章</h3>
    {% if not posts %}
        <div><p>您还没有发表文章哦!</p><a href="{{ url_for('public.edit') }}">去发表一篇试试吧!</a></div>
    {% else %}
        <div class="table-responsive">
            <div class="" style="float:right;">
                搜索：<input type="text" id="dsearch" placeholder="请输入关键词">
            </div>
            <table class="table table-bordered table-hover " id='stable'>
                <thead>
                <tr>
                    <th width="240px">
                        <mark>标题</mark>
                    </th>

                    <th>
                        <mark>时间</mark>
                    </th>
                    <th>
                        <mark>评论</mark>
                    </th>
                    <th>
                        <mark>阅读</mark>
                    </th>
                    <th>
                        <mark>收藏</mark>
                    </th>
                    <th>
                        <mark>公开</mark>
                    </th>
                    <th>
                        <mark>状态</mark>
                    </th>

                    <th>
                        <mark>修改</mark>
                    </th>
                    <th>
                        <mark>删除</mark>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{{ url_for('public.details', id_ = post.id) }}">
                            <h5>{{ post.title|truncate(30, True) }}</h5>
                        </a></td>
                        <td><h5>{{ post.created.strftime('%y-%m-%d') }}</h5></td>
                        <td><h5>{{ post.comment_times|default('0',true) }}</h5></td>
                        <td><h5>{{ post.read_times|default('0',true) }}</h5></td>
                        <td><h5>{{ post.get_col_times()|default('0',true) }}</h5></td>
                        <td><h5>{{ post.get_public()|default('未知',true) }}</h5></td>
                        {% if post.is_public == 0 %}
                            <td><a href="{{ url_for('profile.user_public_manage',id_=post.id,public=1) }}"
                                   class="btn btn-primary">公开</a>
                            </td>
                        {% else %}
                            <td><a href="{{ url_for('profile.user_public_manage',id_=post.id,public=0) }}"
                                   class="btn btn-info">隐藏</a>
                            </td>
                        {% endif %}
                        <td><a href="{{ url_for('public.edit',id_=post.id) }}" class="btn btn-success">修改</a></td>
                        <td><a href="{{ url_for('profile.user_blog_manage',id_=post.id) }}"
                               class="btn btn-danger">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/profile/collects_manage.html
{% extends 'profile/base.html' %}

{% block head_title %}
    {{ title }}
    <title>收藏管理</title>
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ url_for('profile.user_index',username=current_user.username) }}">个人首页</a></li>
        <li class="active">收藏管理</li>
    </ol>
{% endblock %}
{% block right_content %}
    {{ super() }}
    <h3>我收藏的文章</h3>
    <div class="table-responsive">
        <div class="" style="float:right;">
            搜索：<input type="text" id="dsearch" placeholder="请输入关键词">
        </div>
        <table class="table table-bordered table-hover " id='stable'>
            <thead>
            <tr>
                <th>
                    <mark>文章标题</mark>
                </th>
                <th>
                    <mark>文章作者</mark>
                </th>

                <th>
                    <mark>发布时间</mark>
                </th>
                <th>
                    <mark>评论数量</mark>
                </th>
                <th>
                    <mark>阅读数量</mark>
                </th>
                <th>
                    <mark>取消收藏</mark>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr>
                    <td><a href="{{ url_for('public.details', id_ = post.id) }}">
                        <h5>{{ post.title|truncate(22, True) }}</h5>
                    </a></td>
                    <td>
                        {% if current_user.id == post.author.id %}
                            <a href="{{ url_for('profile.user_index', username = post.author.username) }}">
                                <h5>{{ post.author.username }}</h5></a>
                        {% else %}
                            <a href="{{ url_for('profile.others',username=post.author.username) }}">
                                <h5>{{ post.author.username }}</h5></a>
                        {% endif %}
                    </td>
                    <td><h5>{{ post.created.strftime('%Y-%m-%d %H:%M') }}</h5></td>
                    <td><h5>{{ post.comment_times|default('0',true) }}</h5></td>
                    <td><h5>{{ post.read_times|default('0',true) }}</h5></td>
                    <td><a href="{{ url_for('profile.user_collect_manage',id_=post.id) }}"
                           class="btn btn-danger">取消</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/profile/comments_manage.html
{% extends 'profile/base.html' %}

{% block head_title %}
    {{ title }}
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ url_for('profile.user_index',username=current_user.username) }}">个人首页</a></li>
        <li class="active">评论管理</li>
    </ol>
{% endblock %}
{% block right_content %}
    {{ super() }}
    <h3>我发表的评论</h3>
    {% if not comments %}
        <div><p>您还没有发表评论哦!</p><a href="{{ url_for('public.index') }}">先去首页看看文章吧!</a></div>
    {% else %}
        <div class="table-responsive">
            <div class="" style="float:right;">
                搜索：<input type="text" id="dsearch" placeholder="请输入关键词">
            </div>
            <table class="table table-bordered table-hover " id="stable">
                <thead>
                <tr>
                    <th>
                        <mark>博客标题</mark>
                    </th>
                    <th>
                        <mark>评论内容</mark>
                    </th>
                    <th>
                        <mark>评论时间</mark>
                    </th>
                    <th>
                        <mark>删除评论</mark>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for comment in comments %}
                    <tr>
                        <td><a href="{{ url_for('public.details', id_ = comment.post.id) }}">
                            <h5>{{ comment.post.title|truncate(30, True) }}</h5>
                        </a></td>
                        <td><h5>{{ comment.body|striptags|truncate(30, True) }}</h5></td>
                        <td><h5>{{ comment.created.strftime('%Y-%m-%d %H:%M') }}</h5></td>
                        <td><a href="{{ url_for('profile.user_comment_manage',id_=comment.id) }}"
                               class="btn btn-danger">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/profile/todos_manage.html
{% extends 'profile/base.html' %}

{% block head_title %}
    {{ title }}
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{{ url_for('profile.user_index',username=current_user.username) }}">个人首页</a></li>
        <li class="active">TODO管理</li>
    </ol>
{% endblock %}

{% block right_content %}
    {{ super() }}
    <h4>添加TODO</h4>
    <form class="input-group" action="{{ url_for('profile.todo_add') }}" method="post">
        <input class="form-control" id="centent" name="content" type="text" required="required">
        <span class="input-group-btn">
        <button class="btn btn-default" type="submit">添加</button>
    </span>
    </form>
    <br><br>
    <h4>TODO列表</h4>
    <div class="table-responsive">
        <div class="" style="float:right;">
            搜索：<input type="text" id="dsearch" placeholder="请输入关键词">
        </div>
        <table class="table table-bordered table-hover " id="stable">
            <thead>
            <tr>
                <th>
                    <mark>TODO内容</mark>
                </th>

                <th>
                    <mark>创建时间</mark>
                </th>
                <th>
                    <mark>完成时间</mark>
                </th>
                <th>
                    <mark>状态</mark>
                </th>
                <th>
                    <mark>更改状态</mark>
                </th>
                <th>
                    <mark>删除TODO</mark>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for todo in todos %}
                <tr>
                    <td><h5>{{ todo.content|truncate(30, True) }}</h5></td>
                    <td><h5>{{ todo.created.strftime('%Y-%m-%d %H:%M') }}</h5></td>

                    <td>
                        {% if todo.finished %}
                            <h5>{{ todo.finished.strftime('%Y-%m-%d %H:%M') }}</h5>
                        {% else %}
                            <h5>赶快去完成吧</h5>
                        {% endif %}
                    </td>
                    <td><h5>{{ todo.get_status() }}</h5></td>
                    {% if todo.status==0 %}
                        <td><a href="{{ url_for('profile.todo_done',id_=todo.id) }}" class="btn btn-success">已完成</a>
                        </td>
                    {% endif %}
                    {% if todo.status==1 %}
                        <td><a href="{{ url_for('profile.todo_undone',id_=todo.id) }}" class="btn btn-primary">未完成</a>
                        </td>
                    {% endif %}
                    <td><a href="{{ url_for('profile.todo_dele',id_=todo.id) }}" class="btn btn-danger">删除</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}